_name_or_path:
    value: unsloth/Qwen3-1.7B-unsloth-bnb-4bit
_wandb:
    value:
        cli_version: 0.22.1
        e:
            x1swmzbsgibj1a8lhh4h3f18mdsee77g:
                codePath: Continual_learning/dpo/train_dpo.py
                codePathLocal: train_dpo.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "154586963968"
                        used: "135094620160"
                email: hq1@ualberta.ca
                executable: /home/awpc/anaconda3/envs/llm/bin/python
                git:
                    commit: 24bf88b278056c4d88c0bff22c61a0e9c6497f2f
                    remote: https://github.com/iBacklight/LLM.git
                gpu: NVIDIA GeForce RTX 4080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 9728
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4080
                      uuid: GPU-b99eceb1-9ad7-f2a1-0ef5-b7407dbea49f
                host: awpc-Alienware-Aurora-R15
                memory:
                    total: "33348997120"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/awpc/studies/LLMs/Continual_learning/dpo/train_dpo.py
                python: CPython 3.11.13
                root: /home/awpc/studies/LLMs/Continual_learning/dpo
                startedAt: "2025-10-03T05:43:37.670344Z"
                writerId: x1swmzbsgibj1a8lhh4h3f18mdsee77g
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 83
                - 84
                - 95
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 83
                - 84
                - 95
                - 98
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
                - 19
                - 62
                - 66
            "4": 3.11.13
            "5": 0.22.1
            "6": 4.56.2
            "9":
                "1": transformers_trainer
            "12": 0.22.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Qwen3ForCausalLM
attention_bias:
    value: false
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: false
bad_words_ids:
    value: null
base_model_attribute_name:
    value: model
batch_eval_metrics:
    value: false
batch_size:
    value: 1
begin_suppress_tokens:
    value: null
beta:
    value: 0.1
bf16:
    value: true
bf16_full_eval:
    value: true
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: 3407
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: false
dataloader_prefetch_factor:
    value: null
dataset:
    value: combined_pairs
dataset_num_proc:
    value: 36
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_dropout:
    value: true
disable_tqdm:
    value: false
discopop_tau:
    value: 0.05
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dtype:
    value: bfloat16
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 151645
eval_accumulation_steps:
    value: 2
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 50
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
f_alpha_divergence_coef:
    value: 1
f_divergence_type:
    value: reverse_kl
finetuning_task:
    value: null
force_use_ref_model:
    value: false
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
generate_during_eval:
    value: false
gradient_accumulation_steps:
    value: 16
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
head_dim:
    value: 128
hidden_act:
    value: silu
hidden_size:
    value: 2048
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 6144
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_pad_token_id:
    value: -100
label_smoothing:
    value: 0
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_types:
    value:
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
ld_alpha:
    value: null
learning_rate:
    value: 1e-05
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: unsloth_training_checkpoints/runs/Oct02_23-43-44_awpc-Alienware-Aurora-R15
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: false
logging_steps:
    value: 10
logging_strategy:
    value: steps
lora_alpha:
    value: 64
lora_r:
    value: 32
loss_type:
    value: sigmoid
loss_weights:
    value: null
lr_scheduler_type:
    value: cosine
max_completion_length:
    value: null
max_grad_norm:
    value: 1
max_length:
    value: 1024
max_position_embeddings:
    value: 40960
max_prompt_length:
    value: 512
max_seq_length:
    value: 1024
max_steps:
    value: -1
max_window_layers:
    value: 28
metric_for_best_model:
    value: eval_loss
min_length:
    value: 0
model:
    value: unsloth/Qwen3-1.7B-unsloth-bnb-4bit
model/num_parameters:
    value: 1755440128
model_adapter_name:
    value: null
model_init_kwargs:
    value: null
model_type:
    value: qwen3
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 16
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 28
num_key_value_heads:
    value: 8
num_return_sequences:
    value: 1
num_train_epochs:
    value: 1
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ../../../models/transformers/Qwen3-1.7B/DPOTrained
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: null
pad_token_id:
    value: 151654
padding_free:
    value: false
padding_value:
    value: 0
parallelism_config:
    value: null
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping:
                base_model_class: Qwen3ForCausalLM
                parent_library: transformers.models.qwen3.modeling_qwen3
                unsloth_fixed: true
            base_model_name_or_path: unsloth/Qwen3-1.7B-unsloth-bnb-4bit
            bias: none
            corda_config: null
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 64
            lora_bias: false
            lora_dropout: 0.01
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            qalora_group_size: 16
            r: 32
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - k_proj
                - gate_proj
                - down_proj
                - v_proj
                - up_proj
                - o_proj
                - q_proj
            target_parameters: null
            task_type: CAUSAL_LM
            trainable_token_indices: null
            use_dora: false
            use_qalora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 1
per_device_train_batch_size:
    value: 1
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
precompute_ref_batch_size:
    value: null
precompute_ref_log_probs:
    value: false
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
quantization_config:
    value:
        bnb_4bit_compute_dtype: bfloat16
        bnb_4bit_quant_type: nf4
        bnb_4bit_use_double_quant: true
        llm_int8_enable_fp32_cpu_offload: false
        llm_int8_has_fp16_weight: false
        llm_int8_skip_modules: null
        llm_int8_threshold: 6
        load_in_4bit: true
        load_in_8bit: false
        quant_method: bitsandbytes
ray_scope:
    value: last
ref_adapter_name:
    value: null
ref_model_init_kwargs:
    value: null
ref_model_mixup_alpha:
    value: 0.6
ref_model_sync_steps:
    value: 512
reference_free:
    value: false
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value: wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-06
rope_scaling:
    value: null
rope_theta:
    value: 1000000
rpo_alpha:
    value: null
run_name:
    value: qwen3-1.7b-dpo-trl-unsloth
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 100
save_strategy:
    value: steps
save_total_limit:
    value: 2
seed:
    value: 3407
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
sliding_window:
    value: null
suppress_tokens:
    value: null
sync_ref_model:
    value: false
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
tools:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: 250
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.56.2
truncation_mode:
    value: keep_end
typical_p:
    value: 1
unsloth_fixed:
    value: true
unsloth_num_chunks:
    value: -1
unsloth_version:
    value: 2025.9.9
use_4bit:
    value: true
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_liger_loss:
    value: false
use_logits_to_keep:
    value: false
use_mps_device:
    value: false
use_sliding_window:
    value: false
use_weighting:
    value: false
vllm_sampling_params:
    value: null
vocab_size:
    value: 151936
warmup_ratio:
    value: 0.1
warmup_steps:
    value: 0
weight_decay:
    value: 0.01
